### ISSUE TITLE
Requirements gathering with GSA/Richard Speidel

### ISSUE THREAD

**Issue by lbscheidt** [usagov/pangolin#14]
Richard is the Privacy Officer for GSA. His team is responsible for vetting and fulfilling data requests under FOIA (I believe!) and the Privacy Act, and he is on the hook for CASES compliance.

- [x] Schedule
- [x] Interview questions
- [x] Do it
- [ ] Transfer findings into artifacts

Interviewers: @lbscheidt, @em-herrick
Notetakers: @hursey013 @hartsick

**Comment by hartsick** [comment]
I think this is be complete (various artifacts, including notes and -> product brief), so I'm going to move to done! feel free to reopen if not
