### ISSUE TITLE
Tour of existing tech 

### ISSUE THREAD

**Issue by lbscheidt** [usagov/pangolin#16]
- [x] Prep [services overview presentation](https://docs.google.com/presentation/d/1ZFD-GX3_jy1keXl6ku11I1rStf_KbD8a5sRZs9jIwTc/edit#slide=id.g1045a0b5954_0_15)
- [x] Walk through presentation and [services list](https://github.com/usagov/pangolin/wiki/Development-supporting-services) during coworking on 12/2 [will be the 'review' step!]

**Comment by hartsick** [comment]
Planning to have a conversation around [this list](https://github.com/usagov/pangolin/wiki/Development-supporting-services) during coworking on 12/2

**Comment by hartsick** [comment]
WIP presentation [here](https://docs.google.com/presentation/d/1ZFD-GX3_jy1keXl6ku11I1rStf_KbD8a5sRZs9jIwTc/edit#slide=id.g1045a0b5954_0_15). Will be covering all the services listed in the [Wiki list](https://github.com/usagov/pangolin/wiki/Development-supporting-services).

**Comment by hartsick** [comment]
- [ ] Add pay.gov to presentation and list
