### ISSUE TITLE
Review research operations plan

### ISSUE THREAD

**Issue by em-herrick** [usagov/pangolin#21]
Emily, Laura, Aviva to discuss on Weds 11/24

Proposed Plan:
https://docs.google.com/document/d/15y-OSWSlJSv8fRl1dCyBuFdtN8CA_TRD2JpQ4Tr_Mlc/edit#

**Comment by hartsick** [comment]
@em-herrick is this still in-flight, or can we move to another phase?

**Comment by hartsick** [comment]
Closing because of pivot
