### ISSUE TITLE
Set follow-up meeting with Phil to talk Agency Engagement

### ISSUE THREAD

**Issue by em-herrick** [usagov/pangolin#24]
- [x] yes/no
- [x] set target dates
- [x] Determine lead(s)
- [ ] Capture interview findings into Airtable
- [ ] Record action items

Goals
- Discuss near-term vs. long-term lenses
- Share project roadmap/deliverables/goals
- Discuss agency engagement + communications

**Comment by hartsick** [comment]
@em-herrick is this still in flight, or can we close? wasn't sure if interview findings had been recorded
