### ISSUE TITLE
Team Near: Document how we develop products as a team. Includes discussion of who does what, definition of ready, definition of done, etc.

### ISSUE THREAD

**Issue by hartsick** [usagov/pangolin#28]
Write up conversation from [these notes](https://docs.google.com/document/d/1q4MR7ieYvWkw6TPKneAthtot4R6jEBlo-bp1F6meD-M/edit#) in Wiki (expanding [this section](https://github.com/usagov/pangolin/wiki/How-we-track-work)), and propose definitions of ready and done.

For reference, here are few from around TTS:
* Login.gov [Definition of ready](https://handbook.login.gov/articles/definition-of-ready.html)
* Login.gov [Definition of done](https://handbook.login.gov/articles/definition-of-done.html)
* Cloud.gov [how we prioritize work](https://cloud.gov/2021/05/10/how_cloud-gov_prioritizes_organizes_work/)

**Comment by hartsick** [comment]
Done and ready for review! I just updated the "Delivery" section of our [wiki page](https://github.com/usagov/pangolin/wiki/How-we-track-work#delivery). Take a read and let me know what you think. cc @lbscheidt @rahearn 

Of note: to support this way of working, I split the "to do" column on the project board into two columns: "Icebox" and "Backlog". Any newly created issues on the project will automatically be added to Icebox, and we can pull them over as we decide they're ready for tackling. This isn't as important right now while stories are few, but seems useful as we build out the backlog and can't tackle it all at once.

**Comment by rahearn** [comment]
I like that section. Should we also have a wiki page with `Definition of Ready` and `Definition of Done` defined?

**Comment by hartsick** [comment]
@rahearn I thought about that but felt like our team was at the size and stage where I wouldn't yet find those definitions useful. Maybe this is something we could feel out/define as we go and document?
