### ISSUE TITLE
Put together an inventory of TTS services we might use and known gaps in services

### ISSUE THREAD

**Issue by hartsick** [usagov/pangolin#3]

**Comment by hartsick** [comment]
testing

**Comment by hartsick** [comment]
I'm trying out working collaboratively in an issue! Let's see how this feels? I think you should be able to edit my comment if you want to add or edit things in this table.

Took a pass at a list of things we will likely need for this project mapped to my understanding of TTS services:

| name | description | TTS offering | approved non-TTS service |
|--|--|--|--|
| repository | place to put code | - |  Github |
| backlog | place to manage project |  - | Github, Trello |
| CI | something to run automated tests, checks, deploys | - | Github Actions | 
| authentication | account creation and log-in | login.gov | - |
| identity verification | verify someone's identity before granting access to sensitive information | login.gov | - |
| design system | CSS, JS, and static assets representing brand and best practices | USWDS | - |
| analytics | tracking and understanding site visitors | analytics.usa.gov | - |
| monitoring | how we keep tabs on what's happening in our application | - | ? |
| dns | | |
| cdn | | |

things I expect to be covered by PaaS / cloud.gov
| hosting | | |
| database | | |
| static asset storage | | |
| kms | | |
| database | | |
| vpc | | |
| database | | |
| load balancing | | |

product-y sort of things:



| name | description | TTS offering | approved non-TTS service |

It occurs to me there are some other things that TTS could provide help with that aren't really software, but related:
* ATO
* Accessibility audit and 508 compliance

* PaaS
    * Database
    * Redis
    * Server
    * Load balancing
    * Static asset storage
    * KMS / encryption keys
* VPN / exposing of public endpoints
* Security scan / updates
* Signature capture
* Possibly:
    * Email
    * SMS
    * Container registry like Dockerhub
    * Form PaaS
* Aid with:
    * ATO
    * Accessibility audit

**Comment by hursey013** [comment]
@hartsick Just stumbled upon https://digital.gov/services/directory/

**Comment by hartsick** [comment]
I moved this into the Wiki here! Would love to discuss what we think next steps might be. https://github.com/usagov/pangolin/wiki/Development-supporting-services

**Comment by hartsick** [comment]
We discussed next steps at eng sync on 11/23:
1) use time during coworking after Thanksgiving to review with wider team - Christa
1) surface the needed services that don't currently have within TTS to Kelsey - Ryan
