### ISSUE TITLE
Team Manager Duties 12/13-17/10 

### ISSUE THREAD

**Issue by AvivaOskow** [usagov/pangolin#53]
## Monday

- [ ] Reschedule any team ceremonies that have conflicts
- [ ] Assign note-taker and timelord roles at large team meetings for the week
- [ ] Lead the planning session
- [ ] Move notes/issues from the discovery board to the delivery board as needed

## Wednesday

- [ ] Confirm collaboration time agenda per the Slack thread or cancel collaboration time

## Thursday

- [ ] Lead retro OR
- [ ] Ensure the agenda for the demo exists and is shared
- [ ] Write the first draft of the Weekly Ship

## Friday

- [ ] Ship the Weekly Ship
- [ ] Archive any Github notes and issues that are completely finished
- [ ] Pass the torch to the next Team Manager

[Team Manager Schedule](https://docs.google.com/spreadsheets/d/1eMvXJyxjq4Cf2j1OEpD66DcJvPH97g-XSqHda0Irl0c/edit#gid=0)

**Comment by hartsick** [comment]
Going to close this since I started one a little early! https://github.com/usagov/pangolin/issues/50
