### ISSUE TITLE
Synthesize various models of The Platform that are floating around

### ISSUE THREAD

**Issue by lbscheidt** [usagov/pangolin#8]

**Comment by porta-antiporta** [comment]
existing artifacts:
- [US Public digital system](https://www.google.com/url?q=https://docs.google.com/document/d/1qfjaFwAr70b_UyU3a_wrHyZ8Riem76Cz9OfkijXt5rM/edit&sa=D&source=calendar&ust=1638718680253068&usg=AOvVaw0AHGRNmpcjnxy8gtx227Sd)
- [OMB deck](https://www.google.com/url?q=https://drive.google.com/file/d/1-hnbD-NkTh_aWEcpVhJp4N0aAnKRvmE0/view?usp%3Dsharing&sa=D&source=calendar&ust=1638718680253068&usg=AOvVaw0xwYEva-afK12jK55rxkUd)
- [TTS brief brief](https://www.google.com/url?q=https://docs.google.com/document/d/1z21WWqFV_XcJUUhj6lAticaaO4-jS-TEUQcIuUnWcUY/edit&sa=D&source=calendar&ust=1638718680253068&usg=AOvVaw1MfCtUZq-b2NxZRkOUNbCX)
- [Pangolin v2 scary pyramid](https://www.google.com/url?q=https://docs.google.com/presentation/d/1pkE_kTcRAm-qPYYoE8ZHSjZ0OiH_duPlbc9AR4rmGqI/edit%23slide%3Did.gfbab8ff0d6_0_0&sa=D&source=calendar&ust=1638718680253068&usg=AOvVaw294OVJSh9Bgwjg796JoScm)
- - [github wiki](https://github.com/usagov/pangolin/wiki/Development-supporting-services)

**Comment by porta-antiporta** [comment]
Things to cover
1. goal is to create one common artifact(s) that we will look at future state of TTS stack from.
2. this is a starting point, it is expected to change.
3. looking at the artifacts ranges from specific concrete solutions/things v. stated needs.
4. need an end state, but the discussion will need to quickly evolve to "migration/sustenance" to reach an end state that is decades in the making.
5. how this view will help with PMA/CX EO

**Comment by porta-antiporta** [comment]
notes doc - https://docs.google.com/document/d/1IBmT3eclJtrxOBqeqMnOFtV4dRQk3l8JDL9Zg2mR3Lg/edit

**Comment by hartsick** [comment]
@lbscheidt I'm leaving this open because it seems like something we might want to consider as a wrap-up activity. what do you think?

**Comment by hartsick** [comment]
Kelsey has a draft consolidated view; can close this for now

**Comment by porta-antiporta** [comment]
https://gsa.enterprise.slack.com/files/U01J90L65RR/F02P3FU03D0/future_platform_architecture_v3_11.30.2021.jpg
